export const autoData: string[] = [
     "Merhaba",
     "Selam",
     "Nasılsın?",
     "Günaydın",
     "İyi geceler",
     "Teşekkür ederim",
     "Görüşürüz",
     "Hoşça kal",
     "Kendine iyi bak",
     "İyi günler",
     "Üzgünüm",
     "İyi şanslar",
     "İyi çalışmalar",
     "Tanıştığımıza memnun oldum",
     "Kolay gelsin",
     "Neredesin?",
     "Tamam",
     "Anladım",
     "Lütfen",
     "Rica Ederim",
     "Tabii ki",
     "Olur",
     "Bekliyorum",
     "Ne yapıyorsun?",
     "Ne zaman?",
     "Naber?",
     "Hadi",
     "Hadi görüşürüz",
     "Hoş geldin",
     "Hoş bulduk",
     "Evet",
     "Hayır",
     "Belki",
     "Harika!",
     "Süper",
     "Mükemmel",
     "Sağ ol",
     "Yarın görüşürüz",
     "Bir şey sorabilir miyim?",
     "Ne düşünüyorsun?",
     "Gün içinde",
     "Tamamdır",
     "Nasıl ?",
     "Peki",
     "Ben",
     "Sen",
     "Benim",
     "Senin",
];
